### ISSUE TITLE
Add support for ac-3 and ec-3

### ISSUE THREAD

**Issue by avelad** [google/shaka-streamer#37]
Now only it's supported aac and opus. It would be good to expand the supported audio formats.

**Comment by joeyparrish** [comment]
Sounds good.  Thanks for the request!

**Comment by Prototype4988** [comment]
Hi, I'm very much  interested in this project. Could I get more details on it

**Comment by himanshujaidka** [comment]
yes, kindly share more details about this project.

**Comment by dhruvil-shah** [comment]
Hello Sir,
I explored things about working on audio formats and found ffmpeg for the same. I also tried converting a mp4 to ac3 using it and it worked perfectly fine so can I implement the same for the Shaka-Player

**Comment by aryasoni98** [comment]
@avelad I would like to work on this project of GSoC 2021 .  Could I get more details on it .

**Comment by avelad** [comment]
I am not a member of Shaka's team

**Comment by aryasoni98** [comment]
@avelad . oh sorry, I didn't know that .

**Comment by michellezhuogg** [comment]
Hello @aryasoni98 @Prototype4988 @himanshujaidka , sorry for the late reply!
We’re adding a few projects to our projects list soon, please stay tuned via our [mailing list](https://groups.google.com/g/shaka-player-gsoc). This specific project will be off the list since we got a PR for it, and we hope not to waste your time working on the same tasks. 
Please hold to start working on the projects until the GSoC program officially starts. 
If you have questions, please send it to the [Google group](https://groups.google.com/g/shaka-player-gsoc). 
Please be mindful of posting on the Github page just to claim that you are interested in working on a task, since it may spam other developers, and also confuse other students applying for GSoC at the same time. 
Please be kind and only @us for urgent issues on Github regarding your questions, since that might spam the other developers, or team members who are not GSoC mentors. Thank you!
