### ISSUE TITLE
Shaka streamer input media from s3

### ISSUE THREAD

**Issue by praveenkumarpk** [google/shaka-streamer#45]
Hi,
we actually using AWS trasncoding service for our application. In some cases we don't need a managed service for like on-premise setup. so we want to use shaka streamer to package the media input into multiple formats(360p,720p,etc). how to take input dynamically. not like to define static media name and path in input_vod_config.yaml. Is there any way to done that? input from s3? 

*sorry for my english.

**Comment by joeyparrish** [comment]
If I understand you correctly, you'd like to get input from S3 instead of a local file.  Is that correct?

How would you want to access the input from S3?  Via URL, as in "http://bucket.s3.amazonaws.com/foo/bar.mp4"?  Or via some other mechanism?

Would you need this access method to provide credentials?  Or would the input content be publicly accessible from your S3 bucket?

**Comment by joeyparrish** [comment]
Also, do you really need to use Shaka Streamer if you already have an AWS transcoding service?  What Shaka Streamer does is run ffmpeg to transcode for you, then feeds that into a packager.

If you don't need transcoding, you probably don't need Shaka Streamer.  You might be interested in [Shaka Packager](https://github.com/google/shaka-packager), which takes your transcoded files, encrypts them, and produces the DASH manifests & HLS playlists.

Does this help?
