### ISSUE TITLE
Add config for custom bitrates and resolutions

### ISSUE THREAD

**Issue by joeyparrish** [google/shaka-streamer#5]
Right now, the resolutions, their names, and their target bitrates for various codecs are all hard-coded.  It would be nice if the user could customize these through the pipeline config.

**Comment by Brainiarc7** [comment]
**Related:** Support for hardware-based encoding with complex workflows (such as decode with NVDEC + encode with NVENC with multiple GPUs, where jobs are scheduled to specific GPUs, etc) will depend mostly on being able to customize FFmpeg-specific arguments in an encoder pipeline.

I see that at the moment, VAAPI-based encoding is *somehow* supported, but  this implementation assumes platform defaults which could fail in cases where [multiple VAAPI-capable devices exist](https://trac.ffmpeg.org/ticket/7649) or where specific VAAPI drivers need to be set, rather than relying on a hard-coded value such as `i965`. 

Another suggestion would be to extend support for different muxer types in ffmpeg. Of major interest being tee and fifo, which would allow an end user to configure multiple outputs with different weights for latency and error resilience.

**Comment by joeyparrish** [comment]
@Brainiarc7, that's a great point.  Would you please file a separate issue to support multiple VAAPI devices at once?  I think support for different ffmpeg muxers would also be a welcome feature request.  But both seem separate from customizing bitrates and resolutions.  Thanks!

(For what it's worth, we don't hard-code i965 anywhere in the project, but we do mention it as an example in our docs.)
